### ISSUE TITLE
No .exe in .zip

### ISSUE THREAD

**Issue by NIronwolf** [muppet9010/Factorio-Streamlabs-Integration#1]
I know this is AS-IS, but having an issue getting going.  I think I even got it to build, but the .exe it makes crashes.  The readme says there's and .exe in the .zip but it's not there.  :(

If it matters here is the runtime error.

Traceback (most recent call last):
  File "Streamlabs Rcon Integration.py", line 4, in <module>
  File "c:\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Currency.py", line 3, in <module>
ModuleNotFoundError: No module named 'requests'
[19360] Failed to execute script Streamlabs Rcon Integration

**Comment by muppet9010** [comment]
Release published for the most up to date version. This way you won't have to get all of the python pre-reqs installed, just the most basic python install will be sufficent.
